# Generated by Django 5.2.5 on 2025-08-11 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useraccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('products_list', 'Products List'), ('marketing_list', 'Marketing List'), ('order_list', 'Order List'), ('media_plans', 'Media Plans'), ('offer_pricing_skus', 'Offer Pricing SKUs'), ('clients', 'Clients'), ('suppliers', 'Suppliers'), ('customer_support', 'Customer Support'), ('sales_reports', 'Sales Reports'), ('finance_accounting', 'Finance & Accounting')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page_name')},
            },
        ),
    ]
